variables:
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - test
  - deploy

default:
  image: astral/uv:python$PYTHON_VERSION-$BASE_LAYER
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential curl git
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source ~/.cargo/env
    - cargo install cargo-llvm-cov --locked

lint:
  stage: test
  script:
    - uv sync --group lint --extra cpu
    - make lint
  tags:
    - no-gpu

cpu-pytest:
  stage: test
  script:
    - uv sync --group test --extra cpu
    - make cpu-test
    - mv .coverage .coverage.cpu
  artifacts:
    paths:
      - .coverage.cpu
  tags:
    - no-gpu
    - GenuineIntel

# gpu_pytest:
#   stage: test
#   image: pytorch/pytorch:2.5.0-cuda12.4-cudnn9-runtime
#   before_script:
#     - apt update
#     - apt install -y build-essential libhdf5-dev curl
#     - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#     - source ~/.cargo/env
#     - cargo install cargo-nextest
#     - pip install uv
#     - make install
#   script:
#     - make gpu-test
#     - mv .coverage .coverage.gpu
#   artifacts:
#     paths:
#       - .coverage.gpu
#   tags:
#     - gpu


coverage:
  stage: test
  needs:
    - job: cpu-pytest
      artifacts: true
    # - job: gpu_pytest
    #   artifacts: true
  script:
    # - uv run coverage combine .coverage.cpu .coverage.gpu
    - uv run coverage combine .coverage.cpu
    - uv run coverage html -d coverage
    - uv run coverage xml
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  artifacts:
    expose_as: coverage
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - no-gpu
    - GenuineIntel

# pages:
#   stage: deploy
#   script:
#     - apt install -y xvfb libgl1-mesa-glx
#     - make document
#     - mkdir public
#     - mv docs/build/* public/
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
#     - develop
#     - docs/sphinx-update


# .deploy:wheel:
#   stage: deploy
#   script:
#     - uv version $VERSION
#     - uv build
#     - uv publish --username __token__ --password $PYPI_PUBLISH_TOKEN -n -v


# deploy:wheel:tags:
#   image: astral/uv:python$PYTHON_VERSION-$BASE_LAYER
#   extends: .deploy:wheel
#   before_script:
#     - export VERSION=$CI_COMMIT_REF_NAME
#   only:
#     - tags
