[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gridfoam"
version = "0.1.0"
description = "Differentiable Fluid Solver of Hierarchical Grid"
readme = "README.md"
authors = [{ name = "Daichi Ishida", email = "ishida@ricos.co.jp" }]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust",
]
dependencies = [
  "pyvista>=0.44.2",
  "pydantic>=2.11.7",
  "pyyaml>=6.0.2",
  "cubion"
]

[project.optional-dependencies]
cpu = ["torch>=2.5.1", "torchvision>=0.20.1"]
cu118 = ["torch>=2.5.1", "torchvision>=0.20.1"]
cu124 = ["torch>=2.5.1", "torchvision>=0.20.1"]

[dependency-groups]
dev = [
  { include-group = "test" },
  { include-group = "visualize" },
  { include-group = "lint" },
  { include-group = "docs" },
  { include-group = "note" },
]
ci = [
  { include-group = "test" },
  { include-group = "visualize" },
  { include-group = "lint" },
  { include-group = "docs" },
]
benchmark = [
  { include-group = "test" },
  { include-group = "visualize" },
]
test = [
  "pytest",
  "pytest-cov",
  "pytest-benchmark",
  "pytest-memray",
  "pyinstrument",
]
visualize = [
  "polars",
  "plotly",
  "imageio",
  "kaleido"
]
lint = [
  "ruff",
  "jaxtyping",
  "beartype"
]
docs = [
  "sphinx",
  "furo",
  "sphinx-fontawesome",
  "sphinx-gallery",
  "sphinx-design",
  "sphinx-copybutton",
]
note = [
  "ipykernel",
  "ipywidgets",
  "nbstripout>=0.8.1",
  "trame",
  "trame-vtk",
  "trame-vuetify",
]

[tool.uv]
default-groups = ["ci"]
conflicts = [[{ extra = "cpu" }, { extra = "cu118" }, { extra = "cu124" }]]

[tool.uv.sources]
cubion = {path = "lib/cubion"}
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu118", extra = "cu118" },
  { index = "pytorch-cu124", extra = "cu124" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu118", extra = "cu118" },
  { index = "pytorch-cu124", extra = "cu124" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
  "with_benchmark: Run test with pytest-benchmark",
  "with_profile: Run test with memray / pyinstrument",
  "with_device: Run test on cuda device",
]
addopts = [
  "--import-mode=importlib",
  "-m",
  "not with_benchmark and not with_profile and not with_device",
]

[tool.coverage.report]
ignore_errors = false
show_missing = true
# Regexes for lines to exclude from consideration
exclude_also = [
  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",
]
