[package]
name = "cubion"
version = "0.1.0"
edition = "2024"
description = "An extremely fast grid generation library for gridfoam, written in Rust."
readme = "README.md"
authors = ["Daichi Ishida", "ishida@ricos.co.jp"]
keywords = ["physics", "simulation", "grid", "octree", "fluid"]
categories = ["science", "aerospace::simulation"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Math libraries
nalgebra = { version = "0.34.0", features = ["serde-serialize"] }

# Spatial indexing libraries
rstar = { version = "0.12.2", features = ["serde"] }

# Threading libraries
rayon = "1.11.0"

# Hash libraries
wyhash2 = "0.2.1"

# Serialization libraries
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
garde = { version = "0.22.0", features = ["derive"] }

# Python bindings
pyo3 = { version = "0.26", features = ["abi3-py39", "extension-module"] }
numpy = { version = "0.26.0", features = ["nalgebra"] }

# IO libraries
hdf5-metno = "0.10.1"
stl_io = "0.8.5"

# Error handling libraries
thiserror = "2.0.16"

[dev-dependencies]
rstest = "0.26.1"
