[loggers]
keys=root, src, gridfoam, cubion

[logger_root]
level=ERROR
handlers=console

[logger_src]
level=DEBUG
handlers=console
propagate=0
qualname=src,gridfoam

[logger_gridfoam]
level=DEBUG
handlers=console
propagate=0
qualname=gridfoam

[logger_cubion]
level=INFO
handlers=console
qualname=cubion
propagate=0

[handlers]
keys=console

[handler_console]
class=StreamHandler
formatter=generic
args=(sys.stdout, )

[formatters]
keys=generic

[formatter_generic]
class=logging.Formatter
format=[%(asctime)s] [%(levelname)s] [%(process)d] [%(name)s] [%(funcName)s] [%(lineno)d] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
