#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Alternative decomposeParDict name:
decompDict="-decomposeParDict system/decomposeParDict.6"

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication $decompDict decomposePar

runParallel $decompDict snappyHexMesh -overwrite

#- For parallel running: set the initial fields
restore0Dir -processor

runParallel $decompDict patchSummary

runParallel $decompDict potentialFoam -writephi

runParallel $decompDict checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel $decompDict $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar -latestTime

foamToVTK -latestTime

#------------------------------------------------------------------------------
